<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="MyCode.aspx.cs" Inherits="SampleProject.MyCode" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div style="margin-left: 120px">

            <asp:Label ID="Name" runat="server" Text="Name"></asp:Label>
            &nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="txtName" runat="server" required="true"></asp:TextBox>
            <br />
            <br />
            <asp:Label ID="Email" runat="server" Text="Email"></asp:Label>
            &nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="txtEmail" runat="server"></asp:TextBox>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ControlToValidate="txtEmail"
                ForeColor="Red" ValidationExpression="^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$"
                Display="Dynamic" ErrorMessage="Invalid email address" />
            <br />
            <br />
            <asp:Label ID="Phone" runat="server" Text="Phone"></asp:Label>
            &nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="txtPhone" runat="server" required="true"></asp:TextBox>
            <asp:RegularExpressionValidator ID="rev" runat="server" ForeColor="Red" ErrorMessage="Not valid phone number." ControlToValidate="txtPhone" ValidationExpression="^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$" ></asp:RegularExpressionValidator>
            <br />
            <br />
            <asp:Label ID="Address" runat="server" Text="Address"></asp:Label>
            <asp:TextBox ID="txtAddress" runat="server" required="true"></asp:TextBox>
            <br />
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Insert" runat="server" Text="Insert" OnClick="Insert_Click" />

            &nbsp;
        <asp:Label ID="lblstatus" runat="server" Text="" ForeColor="Red"></asp:Label>

            <br />
            <br />

        </div>
        <div>
            <asp:GridView ID="gvEmployees" runat="server" DataKeyNames="Id" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowDeleting="gvEmployees_RowDeleting" OnRowCancelingEdit="gvEmployees_RowCancelingEdit" OnRowEditing="gvEmployees_RowEditing" OnRowUpdating="gvEmployees_RowUpdating">
            </asp:GridView>

        </div>
    </form>
</body>
</html>
